version: 4.0.0.{build}
image: Visual Studio 2017
clone_folder: c:\projects\Moses\
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
install:
- cmd: dotnet restore
build_script:
- cmd: dotnet build ./Moses -c Release
test_script:
- cmd: dotnet test ./Test
artifacts:
- path: Moses\bin\Release\*.nupkg
  name: Nuget_Package