//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moses.Core.Data.EFExtensions {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Messages() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moses.Core.Data.EFExtensions.Messages", typeof(Messages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to More than one entity set supports the given element type &apos;{0}&apos;. You must specify an entity set..
        /// </summary>
        internal static string AmbiguousEntitySet {
            get {
                return ResourceManager.GetString("AmbiguousEntitySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The given type argument to does not match the type of an entity found in the state manager..
        /// </summary>
        internal static string AttachedEntityHasWrongType {
            get {
                return ResourceManager.GetString("AttachedEntityHasWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to retrieve metadata for related end..
        /// </summary>
        internal static string CannotDetermineMetadataForRelatedEnd {
            get {
                return ResourceManager.GetString("CannotDetermineMetadataForRelatedEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Attempting to delete an entity belonging to a different set..
        /// </summary>
        internal static string DeletingFromWrongSet {
            get {
                return ResourceManager.GetString("DeletingFromWrongSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Argument is empty..
        /// </summary>
        internal static string EmptyArgument {
            get {
                return ResourceManager.GetString("EmptyArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The given reader is incompatible with the current materializer. Create a different materializer for this reader..
        /// </summary>
        internal static string IncompatibleReader {
            get {
                return ResourceManager.GetString("IncompatibleReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The given type must implement &apos;{0}&apos; and have a default constructor..
        /// </summary>
        internal static string InvalidOptimizerType {
            get {
                return ResourceManager.GetString("InvalidOptimizerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Source entity did not contribute the given reference..
        /// </summary>
        internal static string InvalidSourceEntity {
            get {
                return ResourceManager.GetString("InvalidSourceEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No entity set was found supporting the given element type &apos;{0}&apos;..
        /// </summary>
        internal static string NoEntitySet {
            get {
                return ResourceManager.GetString("NoEntitySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The argument must be an instance of System.Data.Objects.ObjectQuery&apos;1..
        /// </summary>
        internal static string OperationRequiresObjectQuery {
            get {
                return ResourceManager.GetString("OperationRequiresObjectQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An optimized expression cannot be produced before results have been materialized..
        /// </summary>
        internal static string OptimizedExpressionUnavailable {
            get {
                return ResourceManager.GetString("OptimizedExpressionUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to This method is only supported for non-compound reference keys.
        /// </summary>
        internal static string SimpleKeyOnly {
            get {
                return ResourceManager.GetString("SimpleKeyOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to build a default materialization delegate for this type. Initialize a materializer with a specific delegate definition..
        /// </summary>
        internal static string UnableToCreateDefaultMaterializeDelegate {
            get {
                return ResourceManager.GetString("UnableToCreateDefaultMaterializeDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to find EDM metadata for the given CLR type &apos;{0}&apos;..
        /// </summary>
        internal static string UnableToFindMetadataForType {
            get {
                return ResourceManager.GetString("UnableToFindMetadataForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The given query does not support binding lists..
        /// </summary>
        internal static string UnableToGetBindingList {
            get {
                return ResourceManager.GetString("UnableToGetBindingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unexpected number of key values given..
        /// </summary>
        internal static string UnexpectedKeyCount {
            get {
                return ResourceManager.GetString("UnexpectedKeyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to find specified entity container &apos;{0}&apos;..
        /// </summary>
        internal static string UnknownEntityContainer {
            get {
                return ResourceManager.GetString("UnknownEntityContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to find specified entity set &apos;{0}&apos;..
        /// </summary>
        internal static string UnknownEntitySet {
            get {
                return ResourceManager.GetString("UnknownEntitySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Entity is not tracked by the current object context..
        /// </summary>
        internal static string UntrackedEntity {
            get {
                return ResourceManager.GetString("UntrackedEntity", resourceCulture);
            }
        }
    }
}
